# Generated by Django 5.0.6 on 2024-05-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmgt', '0002_stock_expiration_date_alter_stock_issue_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='issue_quantity',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='receive_quantity',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='reorder_level',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
