# Generated by Django 5.0.4 on 2025-02-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmgt', '0004_cliente_complemento_cliente_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero',
            field=models.CharField(max_length=100),
        ),
    ]
