# Generated by Django 5.0.6 on 2024-05-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmgt', '0005_stock_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='issue_to',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
